# Generated by Django 5.1 on 2025-01-19 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='education_discipline',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='education_level',
            field=models.CharField(choices=[('PHD', 'PhD'), ('MASTERS', 'Masters'), ('UNDERGRAD', 'Undergraduate'), ('ALEVELS', 'A Levels')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='mobile_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='personal_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='position',
            field=models.CharField(choices=[('SE', 'Software Engineer'), ('HR', 'Human Resources'), ('CSR', 'Client Service Representative'), ('SMM', 'Social Media Manager'), ('CA', 'Compliance Analyst')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
