# Generated by Django 5.1 on 2025-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_upload', '0003_cv_admin_notes_cv_rating_cv_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='education_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
